services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/logs

  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    env_file: .env
    volumes:
      - .:/bot
      - ./logs:/logs
