version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  bot:
    build: .
    command: python bot/main.py
    env_file: .env
    volumes:
      - .:/app
