services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    env_file: .env
#    ports:
#      - "8001:8001"
    volumes:
      - .:/app
      - ./logs:/logs

  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    env_file: .env
    volumes:
      - .:/bot
      - ./logs:/logs
